package com.nostrange.app.ai.appfunctions

import com.nostrange.app.ai.prompt.MatchingPromptGenerator
import com.nostrange.app.ai.prompt.ProfilePromptGenerator
import com.nostrange.app.data.repository.CandidateRepository
import com.nostrange.app.data.repository.ProfileRepository
import com.nostrange.app.domain.model.CandidateProfile
import com.nostrange.app.domain.model.UserProfile
import com.nostrange.app.security.KeyStoreManager
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json

/**
 * AppFunctions Integration for Android 16+ System Agents (e.g. Gemini, system assistants).
 *
 * Exposes core Nostrange matchmaking capabilities in a structured, discoverable way.
 * Falls back transparently to Android Share / Intent / Clipboard if AppFunctions is unavailable.
 */
class NostrangeAppFunctions(
    private val profileRepository: ProfileRepository,
    private val candidateRepository: CandidateRepository,
    private val keyStoreManager: KeyStoreManager
) {
    private val json = Json { prettyPrint = true }

    /**
     * Function 1: getProfileQuestionnaire
     * Returns the structured matchmaking questionnaire questions.
     */
    fun getProfileQuestionnaire(): List<String> {
        return listOf(
            "سن شما چقدر است؟",
            "کشور و شهر محل زندگی شما کجاست؟",
            "جنسیت شما چیست و به چه جنسیتی تمایل دارید؟",
            "هدف اصلی شما از رابطه چیست؟ (ازدواج، رابطه بلندمدت، آشنایی)",
            "تمایل به داشتن فرزند دارید؟",
            "سبک زندگی و میزان فعالیت ورزشی، سفر و معاشرت خود را چگونه توصیف می‌کنید؟",
            "ویژگی‌های برجسته شخصیتی شما چیست؟ (میزان استقلال، درونگرایی/برونگرایی، انعطاف‌پذیری)",
            "مهم‌ترین ارزش‌های زندگی شما چیست؟ (صداقت، رشد فکری، خانواده، آزادی)",
            "علایق و سرگرمی‌های شما چیست؟ (کتاب، فناوری، هنر، طبیعت)",
            "معیارهای غیرقابل‌قبول (Deal Breakers) شما برای شریک عاطفی چیست؟"
        )
    }

    /**
     * Function 2: importAiProfileJson
     * Imports structured Profile JSON from the agent into Nostrange.
     */
    suspend fun importAiProfileJson(profileJson: String): Result<UserProfile> {
        return profileRepository.importProfileJson(profileJson)
    }

    /**
     * Function 3: getMatchingCandidates
     * Retrieves top locally filtered candidates for AI ranking.
     */
    suspend fun getMatchingCandidates(limit: Int = 100): List<CandidateProfile> {
        val user = profileRepository.getUserProfileOnce() ?: return emptyList()
        return candidateRepository.runLocalCandidateGeneration(user, limit)
    }

    /**
     * Function 4: createMatchingPrompt
     * Generates ranking prompt containing candidates data for the agent to process.
     */
    suspend fun createMatchingPrompt(limit: Int = 100): String {
        val user = profileRepository.getUserProfileOnce() ?: return "Error: User profile not set."
        val candidates = candidateRepository.runLocalCandidateGeneration(user, limit)
        return MatchingPromptGenerator.generateRankingPrompt(user, candidates)
    }

    /**
     * Function 5: importAiMatchingResult
     * Imports ranked results JSON generated by the agent.
     */
    suspend fun importAiMatchingResult(resultJson: String): Result<Int> {
        return candidateRepository.importAiMatchingResult(resultJson)
    }
}
